import "./globals.css"
import AppShell from "@/components/app-shell"

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased overflow-x-hidden bg-[#07111f] text-white">
        <AppShell>{children}</AppShell>
      </body>
    </html>
  )
}
